### ISSUE TITLE
gy80 readings

### ISSUE THREAD

**Issue by malcriado3d** [kriswiner/GY-80#1]
Hi Kris, tried to use your code removing the display part of the code but could´t make it work.

**Comment by kriswiner** [comment]
What kind of error did you get? I just used it today on a Pro Mini Arduino and Teensy 3.1.

**Comment by kriswiner** [comment]
I'd like to help you use this sketch; please give me a little more information about what did not work. Were you able to read the WHO_AM_I registers? Did you get any data out. Any messages on the Serial output? I am closing this issue and will reopen it when you provide more info.

**Comment by malcriado3d** [comment]
Hi Kris,

sorry for the late reply, as soon as i can i'll paste the errors it gives
me.
Thanks.

Francisco

On Sunday, June 8, 2014, Kris Winer notifications@github.com wrote:

> Closed #1 https://github.com/kriswiner/GY-80/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kriswiner/GY-80/issues/1#event-129178467.

## 

Sent from Gmail Mobile

**Comment by kriswiner** [comment]
I'll  try to help...

**Comment by malcriado3d** [comment]
Thanks a lot! Tonight i'll upload the log.
